language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no test"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./monolith-to-microservices-project/udagram-reverseproxy
  - docker build -t udagram-api-user ./monolith-to-microservices-project/udagram-api-user
  - docker build -t udagram-api-feed ./monolith-to-microservices-project/udagram-api-feed
  - docker build -t udagram-frontend ./monolith-to-microservices-project/udagram-frontend
  
  - docker tag reverseproxy darylnine/reverseproxy:v1
  - docker tag udagram-api-user darylnine/udagram-api-user:v1
  - docker tag udagram-api-feed darylnine/udagram-api-feed:v1
  - docker tag udagram-frontend darylnine/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push darylnine/reverseproxy:v1
  - docker push darylnine/udagram-api-user:v1
  - docker push darylnine/udagram-api-feed:v1
  - docker push darylnine/udagram-frontend:v1

